- name: In momory inventory play
  gather_facts: False
  hosts: localhost
  tasks:  
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result

  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      ansible_ssh_private_key_file: /home/cloud-user/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
    with_items: "{{result.ansible_facts.openstack_servers}}"


  - debug: var=groups
             
- hosts: all 
  gather_facts: false
  tasks:     
  - ping:
  
- name: Good Ansible Role based play
  hosts: all
  become: true
  gather_facts: false   # Speeds up the execution
  roles:

    - role: HAproxy
      when: inventory_hostname in groups['frontends']
      
    - role: apache
      when: inventory_hostname in groups['apps']

    - role: tomcat
      when: inventory_hostname in groups['apps']

    - role: postgresql
      when: inventory_hostname in groups['appdbs']

